import { NextPage } from 'next'
import Head from 'next/Head'
import { Home as HomePage } from 'ui/Home'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Movies App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomePage />
  </div>
)

export default Home
